# MadLib.py
relative = input("Please enter a relative (Aunt, Uncle, Sister ect.): ")
personinroommale = input("Please enter a male person in the room: ")
noun1 = input("Please enter a noun: ")
adj1 = input("Please enter an adjective: ")
school = input("Please enter a school: ")
verb1 = input("Please enter a verb ending in -ing: ")
pluralnoun1 = input("Please enter a plural noun: ")
game = input("Please enter a type of game: ")
adj2 = input("Please enter an adjective: ")
pluralnoun2 = input("Please enter a plural noun: ")
print("\nTen left, so close!\n")
same = input("Please enter the same noun singular: ")
adj3 = input("Please enter an adjective: ")
adj4 = input("Please enter an adjective: ")
animal1 = input("Please enter an animal: ")
animal2 = input("Please enter an animal: ")
noun2 = input("Please enter a noun: ")
adj5 = input("Please enter an adjective: ")
print("\nThree more...\n")
noun3 = input("Please enter a noun: ")
adj6 = input("Please enter an adjective: ")
print ("\nLast one!\n")
noun4 = input("Please enter a noun: ")
print("Thanks! Here is Your Letter of Recomendation.")
print("Dear Director: I would like to recommend my", relative, ",", personinroommale, ",", "for the job of assistant", noun1, "in your", adj1, "camp. He has just graduated from", school, "and has a degree in", verb1, ". He has experience teaching", pluralnoun1, "how to play", game, ". He is ambitious and", adj2, ". During school vacations, he used to work delivering for", pluralnoun2, ", our neighborhood", same, "store. He is a loyal and", adj3, "person and will make a very", adj4, "counselor because he will work like a/an", animal1, "and he is as smart as a/an", animal2,". He is also as honest as the", noun2, "is long. I promise you that this", adj5, noun3, "will make a very", adj6, "counselor for your", noun4, "." )
